name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - name: build the website
      run: |
        npm run build
        git rev-parse --short HEAD > ./output/hash_short
        git rev-parse HEAD > ./output/hash_long
    - uses: actions/upload-artifact@master
      with:
        name: output
        path: ./output/
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: 'gh-pages'
    - name: delete old build
      run: rm -r *
    - uses: actions/download-artifact@master
      with:
        name: output
        path: ./
    - name: commit build
      run: |
        REPO="mvarble/resume"
        SHA_SHORT="$(cat hash_short)"
        SHA_LONG="$(cat hash_long)"
        git config user.email "bot@rodent.club"
        git config user.name "ratbotgenius"
        git add -A
        git commit -m "release [$SHA_SHORT](https://github.com/$REPO/commit/$SHA_LONG)"
    - name: push build
      run: git push
