name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@master
      with:
        name: output
        path: ./output/
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: 'gh-pages'
    - uses: actions/download-artifact@master
      with:
        name: output
        path: ./
    - name: commit build
      run: |
        git config user.email "bot@rodent.club"
        git config user.name "ratbot"
        git add -A
        git commit -m "build for commit to '$(git branch -v --contains main)'"
    - name: push build
      run: git push
        
