name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - name: build the website
      run: |
        npm run build
        git rev-parse --short HEAD > ./output/commit_hash_short
    - uses: actions/upload-artifact@master
      with:
        name: output
        path: ./output/
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: 'gh-pages'
    - name: delete old build
      run: rm -r *
    - uses: actions/download-artifact@master
      with:
        name: output
        path: ./
    - name: commit build
      run: |
        REPO="mvarble/resume"
        SHA_SHORT="$(cat commit_hash_short)"
        git config user.email "bot@rodent.club"
        git config user.name "ratbotgenius"
        git add -A
        git commit -m "automatic build from commit $SHA_SHORT"
    - name: push build
      run: git push
